### ISSUE TITLE
Browing Stops randomly after a period of time

### ISSUE THREAD

**Issue by CompleteComputer** [TechnikEmpire/ss_issue_tracker#21] opened 2015-06-13 17:07 UTC
Browsing stops working at different time intervals. 2 of times, my local area connection showed no internet.

If I turn off the filter, internet is restored.

**Comment by TechnikEmpire** [comment] 2015-06-17 18:54
Possibly related to #23 as this issue caused same effect on Win 8 x64 test machine.

**Comment by TechnikEmpire** [comment] 2015-06-17 19:00
Closing for now assuming that #23 was the cause.

**Closed by TechnikEmpire** 2015-06-17 19:00 UTC
Labels: bug
